name: Gh-Pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - uses: Zishan-7/flutter-gh-pages@v1
      - uses: Zishan-7/flutter-gh-pages@v1
        with:
          useCanvasKit: true
